# Generated by Django 5.1.5 on 2025-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
